### ISSUE TITLE
When using search with string that contains "Ø" it returns a null

### ISSUE THREAD

**Issue by Vetrix68** [DevAndromeda/youtube-sr#37]
Exactly what it says in the title

**Comment by DevAndromeda** [comment]
Hi, I am unable to reproduce this issue. I tested this on both node and deno and it worked as expected in each runtime.

The script is as simple as

```js
console.log(await YouTube.search("Ø"));
```

I've also tested this by adding some other characters along with `Ø` and the results available to me. Maybe it returned `null` for you because the search results for your query were not available?
